# Generated by Django 4.0.6 on 2022-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontent',
            options={'verbose_name': 'Новость контент', 'verbose_name_plural': 'Новости контент'},
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.news', verbose_name='Услуга'),
        ),
    ]
