# Generated by Django 4.0.6 on 2022-12-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название услуги')),
                ('subContent', models.TextField(null=True, verbose_name='Краткое описание услуги')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Url')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография услуги')),
                ('content', models.TextField(null=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название услуги')),
                ('subContent', models.TextField(null=True, verbose_name='Описание услуги')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография услуги')),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга контент',
                'verbose_name_plural': 'Услуги контент',
            },
        ),
    ]
