# Generated by Django 4.0.6 on 2022-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок на слайдере')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография на слайдере')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serviceSlider', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Слайдер (услуги)',
                'verbose_name_plural': 'Сладеры (услуги)',
            },
        ),
    ]
