# Generated by Django 4.0.6 on 2022-12-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_alter_catalogsubcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='catalog.catalogsubcategory', verbose_name='Категория продукта'),
        ),
    ]
