# Generated by Django 4.1.4 on 2022-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productсharacteristic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True, verbose_name='Url'),
        ),
    ]
