# Generated by Django 4.1.4 on 2022-12-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=64, verbose_name='Фото')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drawing', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Чертеж для продукта',
                'verbose_name_plural': 'Чертеж для продуктов',
            },
        ),
    ]
