# Generated by Django 4.0.6 on 2023-01-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_drawing_photo_productsdiscounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('text', models.CharField(max_length=64, verbose_name='Описание')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Каталог на главной странице',
                'verbose_name_plural': 'Каталог на главной странице',
            },
        ),
    ]
