# Generated by Django 4.0.6 on 2023-01-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalogitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.catalogcategory', verbose_name='Категория'),
        ),
    ]
