# Generated by Django 4.0.6 on 2023-01-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_catalogitems_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=64, verbose_name='ИНН')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
