# Generated by Django 4.0.6 on 2023-01-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_requestmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='products',
            field=models.TextField(null=True, verbose_name='Продукты'),
        ),
    ]
