# Generated by Django 4.0.6 on 2023-01-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_requestmessage_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Заявки на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
    ]
